---
- name: Login to cluster
  hosts: eks-cluster

  tasks:
  - name: Copy deployment.yaml
    copy:
      src: deployment.yaml
      dest: deployment.yaml
  - name: Kubernetes Deployment
    shell: cat deployment.yaml | kubectl apply -f - 

